spring.application.name=treasury-backend
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/treasury_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
 
# JWT Secret (change this in production)
jwt.secret=TreasuryFlowSuperSecretKey2024#Omniscient
jwt.expiration=86400000
 
# Port
server.port=8080
